version: '3.9'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./MysqlData:/var/lib/mysql
    networks:
      - red
  backend:
    depends_on:
      - mysqldb
    build: ./backend/.
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
    networks:
      - red
    stdin_open: true
    tty: true
    
  frontend:
    depends_on:
      - backend
    build: ./frontend/.
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - red
    stdin_open: true
    tty: true
    
  
networks:
  red:
    driver: bridge
 